language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - addon-google_apis-google-21

before_install:
 - chmod +x gradlew
 - echo "sdk.dir=$ANDROID_HOME" > local.properties
 - echo "ndk.dir=$ANDROID_HOME" > local.properties

licenses:
 - 'android-sdk-preview-license-52d11cd2'
 - 'android-sdk-license-.+'
